// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: goServer.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: vehicle.proto

package vehicleServer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vehicle message definition
type Vehicle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Number         int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`                                       // vehicle ID
	Direction      string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`                                  // driving direction
	Address        int32                  `protobuf:"varint,3,opt,name=address,proto3" json:"address,omitempty"`                                     // node/vehicle address
	SendVotes      int32                  `protobuf:"varint,4,opt,name=send_votes,json=sendVotes,proto3" json:"send_votes,omitempty"`                // number of votes sent
	ReceiveVotes   int32                  `protobuf:"varint,5,opt,name=receive_votes,json=receiveVotes,proto3" json:"receive_votes,omitempty"`       // number of votes received
	Covehicle      []*Vehicle             `protobuf:"bytes,6,rep,name=covehicle,proto3" json:"covehicle,omitempty"`                                  // vehicles in the same direction group
	RandomNumber   int32                  `protobuf:"varint,7,opt,name=random_number,json=randomNumber,proto3" json:"random_number,omitempty"`       // random number for consensus simulation
	LicensePlate   int32                  `protobuf:"varint,8,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`       // license plate (optional field)
	ElectionTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=election_time,json=electionTime,proto3" json:"election_time,omitempty"`        // timestamp when elected as leader
	ElectionVote   int32                  `protobuf:"varint,10,opt,name=election_vote,json=electionVote,proto3" json:"election_vote,omitempty"`      // votes received in leader election
	ElectionStatus string                 `protobuf:"bytes,11,opt,name=election_status,json=electionStatus,proto3" json:"election_status,omitempty"` // Candidate / Follower
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Vehicle) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Vehicle) GetAddress() int32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Vehicle) GetSendVotes() int32 {
	if x != nil {
		return x.SendVotes
	}
	return 0
}

func (x *Vehicle) GetReceiveVotes() int32 {
	if x != nil {
		return x.ReceiveVotes
	}
	return 0
}

func (x *Vehicle) GetCovehicle() []*Vehicle {
	if x != nil {
		return x.Covehicle
	}
	return nil
}

func (x *Vehicle) GetRandomNumber() int32 {
	if x != nil {
		return x.RandomNumber
	}
	return 0
}

func (x *Vehicle) GetLicensePlate() int32 {
	if x != nil {
		return x.LicensePlate
	}
	return 0
}

func (x *Vehicle) GetElectionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ElectionTime
	}
	return nil
}

func (x *Vehicle) GetElectionVote() int32 {
	if x != nil {
		return x.ElectionVote
	}
	return 0
}

func (x *Vehicle) GetElectionStatus() string {
	if x != nil {
		return x.ElectionStatus
	}
	return ""
}

// Request message definition
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`                                   // vehicle information
	Port          string                 `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`                                         // port of the sender
	TotalVehicles int32                  `protobuf:"varint,3,opt,name=total_vehicles,json=totalVehicles,proto3" json:"total_vehicles,omitempty"` // total number of vehicles involved
	RandomNumber  int32                  `protobuf:"varint,4,opt,name=RandomNumber,proto3" json:"RandomNumber,omitempty"`                        // random value for test simulation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *Request) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Request) GetTotalVehicles() int32 {
	if x != nil {
		return x.TotalVehicles
	}
	return 0
}

func (x *Request) GetRandomNumber() int32 {
	if x != nil {
		return x.RandomNumber
	}
	return 0
}

// Response message definition
type Response struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                              // server message
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                // acknowledged / ignored
	DirectionStatus   string                 `protobuf:"bytes,3,opt,name=direction_status,json=directionStatus,proto3" json:"direction_status,omitempty"`       // True if directions are compatible
	ResponseDirection string                 `protobuf:"bytes,4,opt,name=response_direction,json=responseDirection,proto3" json:"response_direction,omitempty"` // direction of the responding vehicle
	Vehicle           *Vehicle               `protobuf:"bytes,5,opt,name=vehicle,proto3" json:"vehicle,omitempty"`                                              // vehicle information in response
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Response) GetDirectionStatus() string {
	if x != nil {
		return x.DirectionStatus
	}
	return ""
}

func (x *Response) GetResponseDirection() string {
	if x != nil {
		return x.ResponseDirection
	}
	return ""
}

func (x *Response) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

// ConcurrentVehicle message definition
type ConcurrentVehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"` // vehicle information
	Next          *ConcurrentVehicle     `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`       // pointer to next vehicle in list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcurrentVehicle) Reset() {
	*x = ConcurrentVehicle{}
	mi := &file_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrentVehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrentVehicle) ProtoMessage() {}

func (x *ConcurrentVehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrentVehicle.ProtoReflect.Descriptor instead.
func (*ConcurrentVehicle) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *ConcurrentVehicle) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *ConcurrentVehicle) GetNext() *ConcurrentVehicle {
	if x != nil {
		return x.Next
	}
	return nil
}

// VehicleRPC message definition
type VehicleRPC struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Address               int32                  `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`                                                                             // server address
	Vehicles              map[int32]*Vehicle     `protobuf:"bytes,2,rep,name=vehicles,proto3" json:"vehicles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map of all active vehicles
	TotalVehicles         int32                  `protobuf:"varint,3,opt,name=total_vehicles,json=totalVehicles,proto3" json:"total_vehicles,omitempty"`                                            // total number of vehicles
	VoteCount             int32                  `protobuf:"varint,4,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`                                                        // total number of votes
	ConcurrentVehicleList *ConcurrentVehicle     `protobuf:"bytes,5,opt,name=concurrent_vehicle_list,json=concurrentVehicleList,proto3" json:"concurrent_vehicle_list,omitempty"`                   // linked list of vehicles
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VehicleRPC) Reset() {
	*x = VehicleRPC{}
	mi := &file_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleRPC) ProtoMessage() {}

func (x *VehicleRPC) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleRPC.ProtoReflect.Descriptor instead.
func (*VehicleRPC) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *VehicleRPC) GetAddress() int32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *VehicleRPC) GetVehicles() map[int32]*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *VehicleRPC) GetTotalVehicles() int32 {
	if x != nil {
		return x.TotalVehicles
	}
	return 0
}

func (x *VehicleRPC) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *VehicleRPC) GetConcurrentVehicleList() *ConcurrentVehicle {
	if x != nil {
		return x.ConcurrentVehicleList
	}
	return nil
}

var File_vehicle_proto protoreflect.FileDescriptor

const file_vehicle_proto_rawDesc = "" +
	"\n" +
	"\rvehicle.proto\x12\rvehicleServer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n" +
	"\aVehicle\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\x05R\aaddress\x12\x1d\n" +
	"\n" +
	"send_votes\x18\x04 \x01(\x05R\tsendVotes\x12#\n" +
	"\rreceive_votes\x18\x05 \x01(\x05R\freceiveVotes\x124\n" +
	"\tcovehicle\x18\x06 \x03(\v2\x16.vehicleServer.VehicleR\tcovehicle\x12#\n" +
	"\rrandom_number\x18\a \x01(\x05R\frandomNumber\x12#\n" +
	"\rlicense_plate\x18\b \x01(\x05R\flicensePlate\x12?\n" +
	"\relection_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\felectionTime\x12#\n" +
	"\relection_vote\x18\n" +
	" \x01(\x05R\felectionVote\x12'\n" +
	"\x0felection_status\x18\v \x01(\tR\x0eelectionStatus\"\x9a\x01\n" +
	"\aRequest\x120\n" +
	"\avehicle\x18\x01 \x01(\v2\x16.vehicleServer.VehicleR\avehicle\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\tR\x04Port\x12%\n" +
	"\x0etotal_vehicles\x18\x03 \x01(\x05R\rtotalVehicles\x12\"\n" +
	"\fRandomNumber\x18\x04 \x01(\x05R\fRandomNumber\"\xc8\x01\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10direction_status\x18\x03 \x01(\tR\x0fdirectionStatus\x12-\n" +
	"\x12response_direction\x18\x04 \x01(\tR\x11responseDirection\x120\n" +
	"\avehicle\x18\x05 \x01(\v2\x16.vehicleServer.VehicleR\avehicle\"{\n" +
	"\x11ConcurrentVehicle\x120\n" +
	"\avehicle\x18\x01 \x01(\v2\x16.vehicleServer.VehicleR\avehicle\x124\n" +
	"\x04next\x18\x02 \x01(\v2 .vehicleServer.ConcurrentVehicleR\x04next\"\xe0\x02\n" +
	"\n" +
	"VehicleRPC\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\x05R\aaddress\x12C\n" +
	"\bvehicles\x18\x02 \x03(\v2'.vehicleServer.VehicleRPC.VehiclesEntryR\bvehicles\x12%\n" +
	"\x0etotal_vehicles\x18\x03 \x01(\x05R\rtotalVehicles\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x04 \x01(\x05R\tvoteCount\x12X\n" +
	"\x17concurrent_vehicle_list\x18\x05 \x01(\v2 .vehicleServer.ConcurrentVehicleR\x15concurrentVehicleList\x1aS\n" +
	"\rVehiclesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.vehicleServer.VehicleR\x05value:\x028\x012\x9e\x02\n" +
	"\x0eVehicleService\x12A\n" +
	"\x0eReceiveRequest\x12\x16.vehicleServer.Request\x1a\x17.vehicleServer.Response\x12B\n" +
	"\x0fRandomAgreement\x12\x16.vehicleServer.Request\x1a\x17.vehicleServer.Response\x12A\n" +
	"\x0eLeaderElection\x12\x16.vehicleServer.Request\x1a\x17.vehicleServer.Response\x12B\n" +
	"\x0fUpdateVoteCount\x12\x16.vehicleServer.Request\x1a\x17.vehicleServer.ResponseB\x11Z\x0f.;vehicleServerb\x06proto3"

var (
	file_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_proto_rawDescData []byte
)

func file_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)))
	})
	return file_vehicle_proto_rawDescData
}

var file_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vehicle_proto_goTypes = []any{
	(*Vehicle)(nil),               // 0: vehicleServer.Vehicle
	(*Request)(nil),               // 1: vehicleServer.Request
	(*Response)(nil),              // 2: vehicleServer.Response
	(*ConcurrentVehicle)(nil),     // 3: vehicleServer.ConcurrentVehicle
	(*VehicleRPC)(nil),            // 4: vehicleServer.VehicleRPC
	nil,                           // 5: vehicleServer.VehicleRPC.VehiclesEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_vehicle_proto_depIdxs = []int32{
	0,  // 0: vehicleServer.Vehicle.covehicle:type_name -> vehicleServer.Vehicle
	6,  // 1: vehicleServer.Vehicle.election_time:type_name -> google.protobuf.Timestamp
	0,  // 2: vehicleServer.Request.vehicle:type_name -> vehicleServer.Vehicle
	0,  // 3: vehicleServer.Response.vehicle:type_name -> vehicleServer.Vehicle
	0,  // 4: vehicleServer.ConcurrentVehicle.vehicle:type_name -> vehicleServer.Vehicle
	3,  // 5: vehicleServer.ConcurrentVehicle.next:type_name -> vehicleServer.ConcurrentVehicle
	5,  // 6: vehicleServer.VehicleRPC.vehicles:type_name -> vehicleServer.VehicleRPC.VehiclesEntry
	3,  // 7: vehicleServer.VehicleRPC.concurrent_vehicle_list:type_name -> vehicleServer.ConcurrentVehicle
	0,  // 8: vehicleServer.VehicleRPC.VehiclesEntry.value:type_name -> vehicleServer.Vehicle
	1,  // 9: vehicleServer.VehicleService.ReceiveRequest:input_type -> vehicleServer.Request
	1,  // 10: vehicleServer.VehicleService.RandomAgreement:input_type -> vehicleServer.Request
	1,  // 11: vehicleServer.VehicleService.LeaderElection:input_type -> vehicleServer.Request
	1,  // 12: vehicleServer.VehicleService.UpdateVoteCount:input_type -> vehicleServer.Request
	2,  // 13: vehicleServer.VehicleService.ReceiveRequest:output_type -> vehicleServer.Response
	2,  // 14: vehicleServer.VehicleService.RandomAgreement:output_type -> vehicleServer.Response
	2,  // 15: vehicleServer.VehicleService.LeaderElection:output_type -> vehicleServer.Response
	2,  // 16: vehicleServer.VehicleService.UpdateVoteCount:output_type -> vehicleServer.Response
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vehicle_proto_init() }
func file_vehicle_proto_init() {
	if File_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_proto_rawDesc), len(file_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_proto_depIdxs,
		MessageInfos:      file_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_proto = out.File
	file_vehicle_proto_goTypes = nil
	file_vehicle_proto_depIdxs = nil
}
